name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    uses: divkix/reusable-workflows/.github/workflows/pre-commit.yml@main

  automerge-dependabot-pr:
    needs: pre-commit
    uses: divkix/reusable-workflows/.github/workflows/automerge-dependabot-pr.yml@main
